version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: ~/go-task
    steps:
      - checkout
      - run: |
          go test ./... -coverprofile=coverage.txt -covermode=atomic
          go tool cover -html=coverage.txt -o coverage.html
          mv coverage.html /tmp/artifacts
      - run:
          name: Upload code coverage
          command: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
      - store_artifacts:
          path: /tmp/artifacts


