version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: ~/go-task
    steps:
      - checkout
      - run: go test github.com/pedrocelso/go-task/lib/http/controllers
      - run: go test github.com/pedrocelso/go-task/lib/services/user/users_test.go



