version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: ~/go-task
    steps:
      - checkout
      - run:
        command: |
          go test ./... -coverprofile=c.out
          go tool cover -html=c.out -o coverage.html
          mv coverage.html /tmp/artifacts
      - store_artifacts:
        path: /tmp/artifacts



